//! Every route, as one synchronous function: request in, reply out. Axum only wraps it.
use crate::compare::{save_verdict, shadow_rows};
use crate::db::{call_by_id, call_detail, call_summary, get_settings, request_by_id, save_settings, shadows_by_call, CallRow, PROVIDERS};
use crate::decompose::decompose;
use crate::proxy::{execute_call, prune, resolve, second_health, start_shadows, write_shadow, Config};
use crate::util::{iso_ago, now_iso};
use rusqlite::{params, Connection, OptionalExtension};
use serde_json::{json, Value};
use std::path::PathBuf;
use std::sync::Arc;

/// The UI files, compiled into the binary in a release build.
#[derive(rust_embed::RustEmbed)]
#[folder = "../static/"]
struct Assets;

pub struct App {
    pub config: Arc<Config>,
    /// Serve the UI from this directory instead of the embedded files, to edit it without a rebuild.
    pub static_dir: Option<PathBuf>,
}

pub struct Reply {
    pub status: u16,
    pub headers: Vec<(String, String)>,
    pub body: Vec<u8>,
}

/// Any failure below a route becomes a 500 with the message.
pub struct Fail(pub String);
impl<T: std::fmt::Display> From<T> for Fail {
    fn from(e: T) -> Self {
        Fail(e.to_string())
    }
}
type R = Result<Reply, Fail>;

fn json_reply(status: u16, v: Value) -> Reply {
    Reply { status, headers: vec![("Content-Type".into(), "application/json".into())], body: v.to_string().into_bytes() }
}
fn err(status: u16, msg: impl Into<String>) -> Reply {
    json_reply(status, json!({"error": msg.into()}))
}
fn not_found() -> Reply {
    err(404, "not found")
}

pub fn mask_key(key: &str) -> String {
    if key.is_empty() {
        return String::new();
    }
    let head = key.find('_').map_or(0, |i| i + 1);
    if key.chars().count() <= head + 8 {
        return "*".repeat(key.chars().count());
    }
    let chars: Vec<char> = key.chars().collect();
    format!("{}...{}", chars[..head + 4].iter().collect::<String>(), chars[chars.len() - 4..].iter().collect::<String>())
}

const DEFAULT_ITEMS: &str = r#"[{"key": "item_1", "text": ""}]"#;
const DEFAULT_QUESTIONS: &str = r#"[
 {"suffix": "to_the_point", "instructions": "Does {ref} get straight to the point, with no preamble and no over-explanation of the mechanism before or instead of stating the point?", "criteria_true": "Direct, states the point and stops", "criteria_false": "Preamble, hedging, or explains the mechanism before the point"},
 {"suffix": "sounds_human", "instructions": "Does {ref} read as written by a person on a dev team, not generated by an AI?", "criteria_true": "Natural, casual, varied phrasing", "criteria_false": "Robotic: restates the location, over-explains, flat even tone"},
 {"suffix": "is_kiss", "instructions": "Is {ref} as short as it can be while still making sense on its own? One line is the norm, two sentences is the ceiling.", "criteria_true": "As short as possible without losing the point", "criteria_false": "Could be shorter, or needs more context to land"}
]"#;

fn int_param(query: &[(String, String)], name: &str, default: i64, min: i64, max: i64) -> i64 {
    query
        .iter()
        .find(|(k, _)| k == name)
        .and_then(|(_, v)| v.parse::<i64>().ok())
        .map_or(default, |v| v.clamp(min, max))
}

fn providers(app: &App) -> Vec<&'static str> {
    PROVIDERS.iter().copied().filter(|p| *p != "second" || !app.config.second_base_url.is_empty()).collect()
}

fn body_json(body: &[u8]) -> Result<Value, Reply> {
    if body.is_empty() {
        return Ok(json!({}));
    }
    serde_json::from_slice(body).map_err(|e| err(400, format!("invalid JSON body: {e}")))
}

pub fn handle(app: &App, method: &str, target: &str, headers: &[(String, String)], body: &[u8]) -> Reply {
    match route(app, method, target, headers, body) {
        Ok(r) => r,
        Err(Fail(m)) => err(500, m),
    }
}

fn header<'a>(headers: &'a [(String, String)], name: &str) -> Option<&'a str> {
    headers.iter().find(|(k, _)| k.eq_ignore_ascii_case(name)).map(|(_, v)| v.as_str())
}

fn route(app: &App, method: &str, target: &str, headers: &[(String, String)], body: &[u8]) -> R {
    let (path, query_str) = target.split_once('?').unwrap_or((target, ""));
    let query: Vec<(String, String)> = form_urlencoded::parse(query_str.as_bytes()).into_owned().collect();
    let conn = app.config.open_db()?;
    let last_seg = path.rsplit('/').next().unwrap_or("");

    match (method, path) {
        ("GET", "/api/health") => return Ok(json_reply(200, json!({"ok": true}))),
        ("GET", "/api/requests") => {
            let mut stmt = conn.prepare("SELECT id, name, updated_at FROM requests ORDER BY updated_at DESC")?;
            let rows = stmt
                .query_map([], |r| Ok(json!({"id": r.get::<_, i64>(0)?, "name": r.get::<_, String>(1)?, "updatedAt": r.get::<_, String>(2)?})))?
                .collect::<Result<Vec<_>, _>>()?;
            return Ok(json_reply(200, json!(rows)));
        }
        ("POST", "/api/requests") => {
            let b = match body_json(body) { Ok(b) => b, Err(r) => return Ok(r) };
            let now = now_iso();
            conn.execute(
                "INSERT INTO requests (name, model, items_json, questions_json, raw_json_override, last_response, created_at, updated_at) \
                 VALUES (?, 'jev-latest', ?, ?, NULL, NULL, ?, ?)",
                params![b["name"].as_str().unwrap_or("Untitled request"), normalize(DEFAULT_ITEMS), normalize(DEFAULT_QUESTIONS), now, now],
            )?;
            let created = request_by_id(&conn, &conn.last_insert_rowid().to_string())?.unwrap();
            return Ok(json_reply(201, created));
        }
        ("GET", "/api/settings") => {
            let s = get_settings(&conn)?;
            let mut v = s.to_json();
            let o = v.as_object_mut().unwrap();
            o.insert("providers".into(), json!(providers(app)));
            o.insert("second_label".into(), json!(app.config.second_label));
            o.insert("api_key_masked".into(), json!(mask_key(&app.config.api_key)));
            return Ok(json_reply(200, v));
        }
        ("PUT", "/api/settings") => {
            let b = match body_json(body) { Ok(b) => b, Err(r) => return Ok(r) };
            return Ok(match save_settings(&conn, &b["engines"], &b["served"]) {
                Ok(s) => {
                    let mut v = s.to_json();
                    let o = v.as_object_mut().unwrap();
                    o.insert("providers".into(), json!(providers(app)));
                    o.insert("second_label".into(), json!(app.config.second_label));
                    json_reply(200, v)
                }
                Err(m) => err(400, m),
            });
        }
        ("GET", "/api/shadow-compare") => return Ok(json_reply(200, json!({"rows": shadow_rows(&conn, 500)?}))),
        ("GET", "/api/second") => {
            let pending: i64 = conn.query_row("SELECT COUNT(*) FROM shadows WHERE provider = 'second' AND state = 'pending'", [], |r| r.get(0))?;
            let mut v = second_health(&app.config);
            let o = v.as_object_mut().unwrap();
            o.insert("url".into(), json!(app.config.second_base_url));
            o.insert("label".into(), json!(app.config.second_label));
            o.insert("configured".into(), json!(!app.config.second_base_url.is_empty()));
            o.insert("pendingShadows".into(), json!(pending));
            return Ok(json_reply(200, v));
        }
        ("POST", "/api/verdicts") => {
            let b = match body_json(body) { Ok(b) => b, Err(r) => return Ok(r) };
            return Ok(match save_verdict(&conn, &b["callId"], &b["questionId"], &b["verdict"]) {
                Ok(()) => json_reply(200, json!({"ok": true})),
                Err(m) => err(400, m),
            });
        }
        _ => {}
    }

    if method == "GET" && path.starts_with("/api/stats") {
        return stats(&conn, &query);
    }
    if method == "GET" && path.starts_with("/api/calls") {
        return calls(&conn, path, &query);
    }
    if path.starts_with("/api/requests/") {
        match method {
            "GET" => return Ok(request_by_id(&conn, last_seg)?.map_or_else(not_found, |r| json_reply(200, r))),
            "PUT" => return put_request(&conn, last_seg, body),
            "DELETE" => {
                conn.execute("DELETE FROM requests WHERE id = ?", [last_seg])?;
                return Ok(json_reply(200, json!({"deleted": last_seg})));
            }
            _ => {}
        }
    }
    let parts: Vec<&str> = path.split('/').collect();
    if method == "POST" && parts.len() == 5 && parts[1] == "api" && parts[2] == "calls" {
        match parts[4] {
            "run" => return run_on_engine(app, &conn, parts[3], body),
            "promote" => return promote(&conn, parts[3]),
            _ => {}
        }
    }
    if method == "POST" && path.starts_with("/v1/") {
        return proxy(app, &conn, target, headers, body);
    }
    if let Some(reply) = ui_route(app, &conn, method, path, &query, headers, body)? {
        return Ok(reply);
    }
    if method == "GET" {
        return Ok(serve_static(app.static_dir.as_deref(), path));
    }
    Ok(not_found())
}

/// Re-serialise a JSON literal on one line, as it is stored.
fn normalize(text: &str) -> String {
    serde_json::from_str::<Value>(text).unwrap().to_string()
}

fn stats(conn: &Connection, query: &[(String, String)]) -> R {
    Ok(json_reply(200, stats_json(conn, int_param(query, "days", 7, 1, 3650))?))
}

pub fn stats_json(conn: &Connection, days: i64) -> Result<Value, Fail> {
    let cutoff = iso_ago(days * 86400);
    type Row = (i64, bool, i64, i64, String);
    let rows: Vec<Row> = conn
        .prepare("SELECT status, cached, COALESCE(input_tokens, 0), COALESCE(output_tokens, 0), caller FROM calls WHERE ts >= ?")?
        .query_map([&cutoff], |r| Ok((r.get(0)?, r.get::<_, i64>(1)? != 0, r.get(2)?, r.get(3)?, r.get(4)?)))?
        .collect::<Result<_, _>>()?;
    // A TypeSafe shadow is billed like a served call, so its tokens count too.
    let shadows: Vec<(bool, i64, i64)> = conn
        .prepare("SELECT cached, COALESCE(input_tokens, 0), COALESCE(output_tokens, 0) FROM shadows WHERE state = 'done' AND ts >= ?")?
        .query_map([&cutoff], |r| Ok((r.get::<_, i64>(0)? != 0, r.get(1)?, r.get(2)?)))?
        .collect::<Result<_, _>>()?;
    let cached = rows.iter().filter(|r| r.1).count();
    let spent_in: i64 = rows.iter().map(|r| r.2).sum::<i64>() + shadows.iter().map(|s| s.1).sum::<i64>();
    let spent_out: i64 = rows.iter().map(|r| r.3).sum::<i64>() + shadows.iter().map(|s| s.2).sum::<i64>();
    let saved_in: i64 = rows.iter().filter(|r| r.1).map(|r| r.2).sum::<i64>() + shadows.iter().filter(|s| s.0).map(|s| s.1).sum::<i64>();
    let saved_out: i64 = rows.iter().filter(|r| r.1).map(|r| r.3).sum::<i64>() + shadows.iter().filter(|s| s.0).map(|s| s.2).sum::<i64>();
    let callers: std::collections::BTreeSet<&String> = rows.iter().map(|r| &r.4).collect();
    Ok(json!({
        "days": days, "calls": rows.len(), "real": rows.len() - cached, "cached": cached,
        "inputTokens": spent_in, "outputTokens": spent_out,
        "savedInputTokens": saved_in, "savedOutputTokens": saved_out,
        "errors": rows.iter().filter(|r| !(200..300).contains(&r.0)).count(),
        "callers": callers,
    }))
}

fn calls(conn: &Connection, path: &str, query: &[(String, String)]) -> R {
    let tail = path["/api/calls".len()..].trim_matches('/');
    if tail.is_empty() {
        let caller = query.iter().find(|(k, _)| k == "caller").map(|(_, c)| c.as_str());
        return Ok(json_reply(200, json!(calls_list(conn, caller, int_param(query, "limit", 200, 1, 1000))?)));
    }
    let Some(row) = call_by_id(conn, tail)? else { return Ok(not_found()) };
    let shadows = shadows_by_call(conn, &[row.id])?;
    Ok(json_reply(200, call_detail(&row, &shadows[&row.id])))
}

/// The newest calls as summaries, optionally of one caller.
pub fn calls_list(conn: &Connection, caller: Option<&str>, limit: i64) -> Result<Vec<Value>, Fail> {
    let mut sql = "SELECT id, ts, caller, path, model, status, elapsed_ms, cached, attempts, upstream, \
                   input_tokens, output_tokens, request_body FROM calls".to_string();
    let mut args: Vec<rusqlite::types::Value> = vec![];
    if let Some(c) = caller {
        sql += " WHERE caller = ?";
        args.push(c.to_string().into());
    }
    sql += " ORDER BY id DESC LIMIT ?";
    args.push(limit.into());
    let rows: Vec<CallRow> = conn.prepare(&sql)?.query_map(rusqlite::params_from_iter(args), CallRow::from_row)?.collect::<Result<_, _>>()?;
    let ids: Vec<i64> = rows.iter().map(|r| r.id).collect();
    let shadows = shadows_by_call(conn, &ids)?;
    Ok(rows.iter().map(|r| call_summary(r, &shadows[&r.id])).collect())
}

fn put_request(conn: &Connection, id: &str, body: &[u8]) -> R {
    let b = match body_json(body) { Ok(b) => b, Err(r) => return Ok(r) };
    let existing = conn
        .query_row("SELECT name, model, items_json, questions_json, raw_json_override FROM requests WHERE id = ?", [id], |r| {
            Ok((r.get::<_, String>(0)?, r.get::<_, String>(1)?, r.get::<_, String>(2)?, r.get::<_, String>(3)?, r.get::<_, Option<String>>(4)?))
        })
        .optional()?;
    let Some((name, model, items, questions, raw)) = existing else { return Ok(not_found()) };
    let text = |k: &str, old: String| b.get(k).and_then(Value::as_str).map_or(old, String::from);
    let raw = match b.get("rawJsonOverride") {
        Some(Value::String(s)) => Some(s.clone()),
        Some(_) => None,
        None => raw,
    };
    conn.execute(
        "UPDATE requests SET name = ?, model = ?, items_json = ?, questions_json = ?, raw_json_override = ?, updated_at = ? WHERE id = ?",
        params![
            text("name", name), text("model", model),
            b.get("items").map_or(items, Value::to_string), b.get("questions").map_or(questions, Value::to_string),
            raw, now_iso(), id
        ],
    )?;
    Ok(json_reply(200, request_by_id(conn, id)?.unwrap()))
}

fn run_on_engine(app: &App, conn: &Connection, call_id: &str, body: &[u8]) -> R {
    let b = match body_json(body) { Ok(b) => b, Err(r) => return Ok(r) };
    let Some(row) = call_by_id(conn, call_id)? else { return Ok(not_found()) };
    let provider = b["provider"].as_str().unwrap_or("");
    if !PROVIDERS.contains(&provider) {
        return Ok(err(400, format!("unknown engine: {}", if b["provider"].is_null() { "None".into() } else { provider.to_string() })));
    }
    if provider == row.upstream {
        return Ok(err(400, format!("{provider} already served this call")));
    }
    if provider == "typesafe" && app.config.api_key.is_empty() {
        return Ok(err(500, "TYPESAFE_API_KEY not set (environment or .env)"));
    }
    let resolved = resolve(conn, provider, &row.path, row.request_body.as_bytes(), &app.config, false)?;
    write_shadow(conn, row.id, provider, "done", Some(&resolved), None)?;
    let shadows = shadows_by_call(conn, &[row.id])?;
    Ok(json_reply(200, call_detail(&row, &shadows[&row.id])))
}

fn promote(conn: &Connection, call_id: &str) -> R {
    Ok(promote_call(conn, call_id).map_err(Fail)?.map_or_else(not_found, |v| json_reply(201, v)))
}

/// Turns a recorded call into a saved request. None when the call does not exist.
pub fn promote_call(conn: &Connection, call_id: &str) -> Result<Option<Value>, String> {
    let e = |e: rusqlite::Error| e.to_string();
    let Some(row) = call_by_id(conn, call_id).map_err(e)? else { return Ok(None) };
    let now = now_iso();
    // The passthrough records an upstream body verbatim, so it may not be JSON.
    let last_body: Value = row.response_body.as_deref().filter(|b| !b.is_empty()).and_then(|b| serde_json::from_str(b).ok()).unwrap_or(Value::Null);
    let shape = serde_json::from_str::<Value>(&row.request_body).ok().and_then(|b| decompose(&b));
    // A body the form cannot rebuild exactly stays a raw override, so a send replays what was recorded.
    let (items, questions) = shape.clone().unwrap_or_default();
    conn.execute(
        "INSERT INTO requests (name, model, items_json, questions_json, raw_json_override, last_response, created_at, updated_at) \
         VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
        params![
            format!("{} @ {}", row.caller, row.ts), row.model.clone().unwrap_or_else(|| "jev-latest".into()),
            json!(items).to_string(), json!(questions).to_string(),
            if shape.is_some() { None } else { Some(row.request_body.clone()) },
            json!({"status": row.status, "body": last_body, "elapsedMs": row.elapsed_ms}).to_string(),
            now, now
        ],
    ).map_err(e)?;
    Ok(request_by_id(conn, &conn.last_insert_rowid().to_string()).map_err(e)?)
}

/// Answer from the served engine, then run the other enabled engines as shadows.
fn proxy(app: &App, conn: &Connection, path: &str, headers: &[(String, String)], body: &[u8]) -> R {
    let bypass = header(headers, "X-Jev-Cache") == Some("0");
    let settings = get_settings(conn)?;
    let served = settings.served.clone();
    // A second upstream may need no key, so only a served TypeSafe call needs one.
    if served == "typesafe" && app.config.api_key.is_empty() {
        return Ok(err(500, "TYPESAFE_API_KEY not set (environment or .env)"));
    }
    let result = execute_call(conn, path, body, header(headers, "X-Jev-Caller").unwrap_or("unknown"), &app.config, &served, bypass)?;
    let shadows: Vec<String> = settings.engines.iter().filter(|e| **e != served).cloned().collect();
    start_shadows(&app.config, result.call_id, &shadows, path, body, bypass);

    let (status, payload) = if result.status == 0 {
        // A locally generated 502 still carries the X-Jev-* headers so a caller can correlate it
        // with the recorded row, plus the real upstream status (0).
        let message = if result.upstream == "second" {
            format!("{} unreachable at {}", app.config.second_label, app.config.second_base_url)
        } else {
            "upstream unreachable".into()
        };
        (502, json!({"error": message}).to_string())
    } else {
        (result.status as u16, result.body.clone())
    };
    let mut h = vec![
        ("Content-Type".to_string(), "application/json".to_string()),
        ("X-Jev-Elapsed-Ms".into(), result.elapsed_ms.to_string()),
        ("X-Jev-Cache".into(), if result.cached { "HIT" } else { "MISS" }.into()),
        ("X-Jev-Call-Id".into(), result.call_id.to_string()),
        ("X-Jev-Attempts".into(), result.attempts.max(1).to_string()),
    ];
    if result.status == 0 {
        h.push(("X-Jev-Upstream-Status".into(), "0".into()));
    }
    h.push(("X-Jev-Upstream".into(), result.upstream.clone()));
    h.push(("X-Jev-Shadows".into(), shadows.join(",")));
    Ok(Reply { status, headers: h, body: payload.into_bytes() })
}

fn serve_static(dir: Option<&std::path::Path>, path: &str) -> Reply {
    let rel = path.strip_prefix("/static/").unwrap_or(path).trim_start_matches('/');
    let missing = || Reply { status: 404, headers: vec![], body: vec![] };
    let body = match dir {
        Some(dir) => {
            let Ok(base) = dir.canonicalize() else { return missing() };
            match base.join(rel).canonicalize() {
                Ok(f) if f.starts_with(&base) && f.is_file() => std::fs::read(f).ok(),
                _ => None,
            }
        }
        None => Assets::get(rel).map(|f| f.data.into_owned()),
    };
    let Some(body) = body else { return missing() };
    let content_type = match rel.rsplit('.').next() {
        Some("js") => "application/javascript",
        Some("css") => "text/css",
        Some("woff2") => "font/woff2",
        _ => "text/html",
    };
    // The UI files change while the server runs, so a plain reload must fetch them again.
    Reply { status: 200, headers: vec![("Content-Type".into(), content_type.into()), ("Cache-Control".into(), "no-cache".into())], body }
}

fn ui_route(app: &App, conn: &Connection, method: &str, path: &str, query: &[(String, String)], headers: &[(String, String)], body: &[u8]) -> Result<Option<Reply>, Fail> {
    let form: Vec<(String, String)> = if header(headers, "Content-Type").is_some_and(|c| c.starts_with("application/x-www-form-urlencoded")) {
        form_urlencoded::parse(body).into_owned().collect()
    } else {
        vec![]
    };
    crate::ui::handle(&crate::ui::Req { app, conn, method, path, query, headers, form })
}

pub fn run_prune(config: &Config, days: i64) -> Result<String, Fail> {
    let conn = config.open_db()?;
    let (calls, cache) = prune(&conn, days)?;
    Ok(format!("pruned {calls} calls and {cache} cache rows older than {days} days"))
}

